version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/hw3-frontend/
      dockerfile: Dockerfile
    image: hw3-frontend:0.0.1
    ports: 
      - "4200:4200"
    container_name: frontend

  backend: 
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: hw3-backend:0.0.1
    ports: 
      - "8080:8080"
    container_name: backend